### ISSUE TITLE
Compartilhamento do Documento de Visão 

### ISSUE THREAD

**Issue by fpenha** [fpenha/escola-karate#1]

**Comment by fpenha** [comment]
Reestruturar a documentação, antes DOCX, para utilizar os recursos do Google Docs

**Comment by fpenha** [comment]
Foi criado uma estrutura no drive e compartilhado com todos. Acredito que o link do compartilhamento tenha chegado no email de vocês. @evertonaugusto @DennyHappy @Lauridas @

**Comment by evertonaugusto** [comment]
link do documento de visão compartilhado por @victorO13  https://docs.google.com/document/d/1ZL1SL-HMjBlqaJWrbhfOxMbcho1QCqYwKYqrD3L76EI/edit
