### ISSUE TITLE
Leitura do documento para discussão em sala

### ISSUE THREAD

**Issue by fpenha** [fpenha/escola-karate#2]

**Comment by fpenha** [comment]
Uma leitura coletiva e explanativa sobre o problema descrito no documento de visão foi realizada. Diante da compreensão e discussão, a equipe de desenvolvimento foi provocado para gerar um pequeno esboço da análise inicial, através do diagrama de caso de uso e das potências classes para o diagrama. 

@evertonaugusto , por favor, anexe o resultado (esboço inicial) da nossa conversa que colocamos no quadro.

**Comment by fpenha** [comment]
@evertonaugusto , assim que postar a imagem, feche a feche esta tarefa.

**Comment by evertonaugusto** [comment]
![24941790-7717-4827-93f8-554b5f2057c3](https://user-images.githubusercontent.com/32283100/58123654-b752e800-7be2-11e9-817d-76030a2eb1dd.JPG)
