### ISSUE TITLE
Estruturação de diretório do repositório

### ISSUE THREAD

**Issue by fpenha** [fpenha/escola-karate#3]
Compreender a estruturação de diretório para projetos e trazer uma proposta para o nosso repositório.  Analisem os possíveis arquivos/artefatos que estarão no nosso projeto e, de acordo com o propósitos deles, agrupem na estrutura proposta.

**Comment by DennyHappy** [comment]
Sobre padrões para organização de estrutura de pastas em projetos php, vi que existem dois tipos muito utilizados, o Laravel e o Symfony, que são utilizados por Frameworks famosos para organização de diretórios. 
https://laravel.com/docs/5.3/structure#the-root-directory
https://symfony.com/doc/current/quick_tour/the_architecture.html
Fica como proposta de debate para o proximo encontro.

**Comment by ramonfsilva** [comment]
> 
> 
> Sobre padrões para organização de estrutura de pastas em projetos php, vi que existem dois tipos muito utilizados, o Laravel e o Symfony, que são utilizados por Frameworks famosos para organização de diretórios.
> https://laravel.com/docs/5.3/structure#the-root-directory
> https://symfony.com/doc/current/quick_tour/the_architecture.html
> Fica como proposta de debate para o proximo encontro.

**Comment by DennyHappy** [comment]
Eu e Ramon ficaremos responsaveis pela estruturação d diretorios do sistema

**Comment by ramonfsilva** [comment]
I'm taking a look at the links cited by @DennyHappy

**Comment by ramonfsilva** [comment]
help video conceptualizing about the MVC model
https://www.youtube.com/watch?v=HEHsNvUIT1g
Explanatory link exemplifying the contents of the Model, View and Controller layers
https://book.cakephp.org/2.0/pt/cakephp-overview/understanding-model-view-controller.html

**Comment by DennyHappy** [comment]
For the presentation of the next project development interaction, we will show a brief explanation of the MVC project pattern and a sketch of the implementation of our system based on it.
Presentation tools: slide, photo

**Comment by ramonfsilva** [comment]
after a brief search on the mvc, a brief explanation was made about the subject and how it could be applied in our project. joining the ideas of @DennyHappy  and my, we got the following result:
[Estru-Direretorios.pptx](https://github.com/fpenha/escola-karate/files/3221506/Estru-Direretorios.pptx)
