### ISSUE TITLE
Prototipação de Tela e Revisão do Esboço

### ISSUE THREAD

**Issue by fpenha** [fpenha/escola-karate#4]
Diante do esboço realizado em sala de aula, uma prototipação deverá ser realizada com intuito de apresentar um visualização que será trabalhada, como também revisar os conceitos que foram trabalhando através de uma análise com a ferramenta [DojoWEB](https://dojoweb.com.br/)

**Comment by DennyHappy** [comment]
A prototipação foi realizada com base no modelo *Dashboard*, onde os papeis terão sua área especifica
![WhatsApp Image 2019-05-26 at 11 14 39 PM](https://user-images.githubusercontent.com/38359583/58818251-01d15d00-8604-11e9-8084-0e8ac81be385.jpeg)
