### ISSUE TITLE
Diagramas UC e Classes

### ISSUE THREAD

**Issue by fpenha** [fpenha/escola-karate#5]
Em sala de aula, realizou-se um desenho informal de UML, porém, esta tarefa é para ser representado, formalmente, os conceitos que foram discutidos.

**Comment by ramonfsilva** [comment]
blob:https://web.whatsapp.com/fffa1d07-c365-4ec2-a719-da3781499b3f

**Comment by ramonfsilva** [comment]
Segue abaixo as fotos relacionados a  criação dos DCU e DC, referentes a discussão da aula passada.

![WhatsApp Image 2019-05-21 at 14 33 59](https://user-images.githubusercontent.com/45216995/58285962-2ca9ee80-7d84-11e9-90d3-40eeff3596e7.jpeg)
![WhatsApp Image 2019-05-21 at 14 33 58](https://user-images.githubusercontent.com/45216995/58285963-2ca9ee80-7d84-11e9-821f-0de81fbf49ec.jpeg)

**Comment by evertonaugusto** [comment]
Let us divide this problem into two parts.
I'll be responsible for the use cases, @victorO13 and @ViniciusG17 will be responsible for creating the class diagram.

**Comment by victorO13** [comment]
iniciarei o diagrama de classe

**Comment by evertonaugusto** [comment]
I'll start the use case diagram now

**Comment by evertonaugusto** [comment]
**Below, I present use case diagrams developed to better understand the scope and main features of the karate school system.**



***Diagram 1: student enrollment process.***

![1_Matricula](https://user-images.githubusercontent.com/32283100/58375657-59016e80-7f2e-11e9-93be-238cda6add6d.png)


***Diagram 2: payment process and confirmation of registration.***

![2_Pagamento Mensalidade](https://user-images.githubusercontent.com/32283100/58375658-59016e80-7f2e-11e9-91ee-9e451476d785.png)

***Diagram 3: event Creation, Management, and Registration Process.***

![3_Evento](https://user-images.githubusercontent.com/32283100/58375659-59016e80-7f2e-11e9-8d18-58b9aebed4ab.png)

***Diagram 4: payment scenario for teacher and secretary***

![4_Pagamento de professor e seretario](https://user-images.githubusercontent.com/32283100/58376439-aa672900-7f41-11e9-9bc9-e52e9b822661.png)



It is worth remembering that these diagrams are open for discussion.
Waiting feedback!!

**Comment by victorO13** [comment]
**below, I present a class diagram drawn formally according to what was discussed in the room**
![WhatsApp Image 2019-05-26 at 15 11 00](https://user-images.githubusercontent.com/50842019/58385673-8d2a6d00-7fca-11e9-979e-c51fbb9812ad.jpeg)

**Comment by DennyHappy** [comment]
Após uma revisão dos casos de uso e diagrama de classes criados, foram indicadas algumas correções que serão realizadas na próxima iteração
