### ISSUE TITLE
Prototipo Funcional

### ISSUE THREAD

**Issue by ramonfsilva** [fpenha/escola-karate#6]
Primeira Etapa: Definir o que será necessário para elaborar um protótipo funcional baseado no caso de uso "pagamento de mensalidade";
Segunda Etapa: De acordo com a etapa anterior criar um protótipo em html/php para manipulação das informações associadas ao caso de uso;

**Comment by DennyHappy** [comment]
Envio de documentação para pasta compartilhada no Google Drive.
https://drive.google.com/open?id=1wPeb4xGDmnnaI3JTrpaE1J1YgWWFmSmm
Conteúdo:
.DOC explanando o que é necessário para elaboração do protótipo funcional;
---Definição de: 
------Interações e os envolvidos/entidades;
------Como eles se relacionam entre no domínio;
------E as funcionalidades executadas por eles.
.Sql de criação do banco de dados.
.Zip com tela modelo para interface de usuário.

**Comment by DennyHappy** [comment]
Analisar o detalhamento #7 
![WhatsApp Image 2019-06-04 at 2 22 41 PM](https://user-images.githubusercontent.com/38359583/58899869-52b08680-86d4-11e9-92d1-f5e5f1aaf709.jpeg)

**Comment by ramonfsilva** [comment]
Após uma reunião e discussão em relação a tela de pagamento foi elaborado o seguinte esboço de tela: 
![tela-pagamento](https://user-images.githubusercontent.com/45216995/59630267-4cca9480-911b-11e9-9a84-c12d7d06df31.jpg)

**Comment by ramonfsilva** [comment]
Levando em consideração questões como navegabilidade, Design e funcionalidades algumas mudanças foram executadas no esboço acima, assim foi feito o Modelo viável após análise complementar:
![esboço_tela](https://user-images.githubusercontent.com/45216995/59641850-464b1580-9139-11e9-8fd6-799ec872fa1b.jpg)
Fluxo Principal e alternativo contido em #7
