### ISSUE TITLE
Detalhamento de pagamento salarial

### ISSUE THREAD

**Issue by DennyHappy** [fpenha/escola-karate#7]
Definir os conceitos intrínsecos aos pagamentos salariais do Professor e Secretario.
Por exemplo:
Forma de calculo salarial do professor e do secretario.

**Comment by DennyHappy** [comment]
Pagamento salarial:
Professores - tipo (Horista, Fixo) independente da quantidade de turma, o tipo Fixo deve ganha por um quantitativo máximo de turmas ministradas
![WhatsApp Image 2019-06-03 at 2 32 42 PM](https://user-images.githubusercontent.com/38359583/58821963-aa83ba80-860c-11e9-916e-834b583d53aa.jpeg)

Convidados do evento

**Comment by DennyHappy** [comment]
PROBLEMA: CASO O PROFESSOR FALTE, SERÁ LANÇADO UMA FALTA, DITO ISSO CADA PROFESSOR TERÁ UMA FREQUÊNCIA DE AULAS, PODENDO SER REGISTRADA UMA FALTA PARA QUE SEJA DESCONTADO NO CALCULO DE SEU PAGAMENTO SALARIAL. 
![WhatsApp Image 2019-06-04 at 1 34 03 PM](https://user-images.githubusercontent.com/38359583/58896995-ae2b4600-86cd-11e9-8f55-a485442f41c3.jpeg)

**Comment by DennyHappy** [comment]
Atores: Gerente, Sistema			Realizar pagamento
Fluxo principal:
1 - O Gerente solicita a listagem dos profs. pendentes dentro de um periodo de tempo
2 - O sistema responde com os dados solicitação [D.1]
3 - Em um componente de Busca Rapida, o gerente solicita o nome desejado (opcional), em conjunto ele pode selecionar um intervalo de tempo (obrigatório) que mostra os professores pendentes.
Fluxo altenativo:
F.A.1 - Garantirá que as pensquisas feitas contenham os dados necessarios atraves de mensagens de alerta/ajuda
COMPLEMENTOS
Paginação - quantidade maxima de conteudo apresentado por página.
Busca rápida - busca diferenciada de professores - por nome.
CHECAR PAGAMENTO - MODAL APRESENTANDO INFORMES DO PROF. APÓS A CHECAGEM ATUALIZAM-SE OS DADOS E RETORNA A LISTAGEM ANTERIOR.

**Comment by DennyHappy** [comment]
Classes Identificadas
Professor 	<tem>		Modelo de contratação(horista/fixo)
Professor 	<tem>		1 ... 3		Turmas
Turmas 	        <contem>	1		Professor
Professor 	<tem>		Frequência 	
Frequência 	<tem>		Faltas
Faltas 		<tem>		Justificativa

**Comment by Lauridas** [comment]
Detalhamento diagrama de classe - Pagamento Salarial
![image](https://user-images.githubusercontent.com/40182444/58977702-a25c8400-87a0-11e9-8f84-55d74c4bd82c.png)

**Comment by ramonfsilva** [comment]
Documento descrevendo as classes no cenário de pagamento de salário. 
https://drive.google.com/open?id=1sgxbB8sg_hFIBOceYf8QUvnrLwpWpat4.

**Comment by ramonfsilva** [comment]
Template de especificação do caso de uso:
https://edisciplinas.usp.br/mod/resource/view.php?id=1104118

**Comment by ramonfsilva** [comment]
Após uma reunião e discussão em relação a tela de pagamento foi elaborado o seguinte esboço de tela: 
![tela-pagamento](https://user-images.githubusercontent.com/45216995/59630267-4cca9480-911b-11e9-9a84-c12d7d06df31.jpg)

Tendo uma opção no navbar (pagamentos) relacionada aos pagamentos pendentes e outra com os confirmados aonde o gerente irá escolher qual tipo deseja.
Ao escolher o tipo de pagamento, o gerente deve escolher o tipo de usuário. (professor,aluno,secretario, nesse esboço será focado o tipo professor) e também poderá escolher uma data especifica.
Ao selecionar o tipo, o sistema deve responder com os dados solicitados, com os campos:
Nome,modo de contratação,data,faltas,salario total, salario calculado e botão "Confirmar Pagamento".(No caso de pendentes)
Ao apertar o botão "Confirmar Pagamento" um modal deve ter a senha do professor confirmando que recebeu o pagamento, com os botões "confirmar" e "Cancelar".
Feito essa ação os dados retornaram atualizados.

Questionamento - (Busca Rápida se encaixa na ocasião)
No modal pode haver a matricula e senha do professor para melhor identificação.

**Comment by ramonfsilva** [comment]
Levando em consideração questões como navegabilidade, Design e funcionalidades algumas mudanças foram executadas no esboço acima, assim foi feito o Modelo viável após análise complementar:
![esboço_tela](https://user-images.githubusercontent.com/45216995/59641850-464b1580-9139-11e9-8fd6-799ec872fa1b.jpg)

Atores: Gerente, Sistema	--------------------------------------------Realizar pagamento/pagamentos confirmados
(foco nos pagamentos dos professores pendentes)
Fluxo principal:
1 - O gerente vai até a opção no navbar (pagamentos) relacionada aos pagamentos pendentes e outra com os confirmados;

2- Escolher uma das opções na aba pagamentos que ele deseja;

3- No caso de "pendentes" irá constar três botões de navegação  (Professor, Aluno, Secretaria) e abaixo deles as caixas de input Dia e Mês e "IR"para determinar a data especifica;

4 - Selecionando o botão "Professor" e os campos de seleção de data e botão "IR"; F.A.1

5- Uma tabela com as informações "Nome","Modo contratação","Data","Faltas","Salario Base" e "Salario" e o botão "Realizar Pagamento";F.A.2 (tais informações podem ser alteradas de acordo com a categoria selecionada)

6 - Ao apertar o botão "Confirmar Pagamento";

7 - Uma caixa de dialogo de confirmação será aberta com os campos da "Matricula" e "Senha"  do professor selecionado e os botões Confirmar e Cancelar;

8 - Tais campos deverá ser preenchido pelo professor selecionado confirmando o pagamento;

9- Caso os dados inseridos sejam coerentes ao professor a confirmação de pagamento é efetuada;F.A.3

10 - Os dados retornarão atualizados ao sistema.

Fluxo Alternativo:(Exceções)
1 - Garantirá que as pesquisas feitas contenham os dados necessários através de mensagens de alerta/ajuda;

2 - Caso as informações não constar na tela, possíveis causas serão listadas, como:
Nenhum cadastro da categoria especifica;
Data inserida não consta em nenhuma pessoa;
e outros.

3 - Caso os dados inseridos na confirmação do pagamento um aviso será exibido indicando erro na senha.

Implementações a serem discutidas:
Busca rápida nas categorias.

**Comment by ramonfsilva** [comment]
Novo modelo para página filtro de listagem de pagamentos.
![WhatsApp Image 2019-06-24 at 19 27 13](https://user-images.githubusercontent.com/45216995/60059852-93dcfa80-96c4-11e9-9456-8e88420c6bc4.jpeg)
